[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "daamath"
version = "0.5.5"
#dynamic = ["version"]
description = "a mathematician's spellbook"
readme = "readme.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.10"

authors = [
    { name = "deftasparagusanaconda" }
]

keywords = [
    "math",
    "numerical",
    "algebra",
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Mathematics",   
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"   
]

dependencies = ['pyfma']

[project.urls]
Homepage = "https://github.com/deftasparagusanaconda/daamath"
Documentation = "https://deftasparagusanaconda.github.io/daamath/"
Repository = "https://github.com/deftasparagusanaconda/daamath"
Issues = "https://github.com/deftasparagusanaconda/daamath/issues"

#[tool.hatch.build.targets.wheel]
#packages = ["/src/daamath"]

#[tool.hatch.version]
#path = "implementations/python/src/daamath/__init__.py"
