ring = '∘'
asterisk = '∗'
bullet = '∙'
tilde = '∼'
tilde_reversed = '∽'
dot = '⋅'
dot_squared = '⊡'
dot_circled = '⊙'
dot_circled_big = '⨀'
reverse_solidus = '⧵'
diamond = '⋄'
star = '⋆'
triple_colon = '⫶'
from . import root
