from . import western_arabic
from . import duodecimal
from . import devanagari
from . import eastern_arabic
from . import bengali
from . import gujarati
from . import gurmukhi
from . import odia
from . import tamil
from . import kannada
from . import telugu
from . import malayalam
from . import thai
from . import khmer
from . import myanmar
from . import tibetan
from . import lao
