roman_numeral_upper = 'ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩⅪⅫ        ⅬⅭⅮⅯ'
roman_numeral_lower = 'ⅰⅱⅲⅳⅴⅵⅶⅷⅸⅹⅺⅻ        ⅼⅽⅾⅿ'
counting_rod_vertical = '〇𝍩𝍪𝍫𝍬𝍭𝍮𝍯𝍰𝍱'
counting_rod_horizontal = '〇𝍠𝍡𝍢𝍣𝍤𝍥𝍦𝍧𝍨'
counting_rod_negative = 'U+20E5'
tally_mark = '𝍷   𝍸'
tally_mark_ideographic = '𝍲𝍳𝍴𝍵𝍶'
decimal_exponent = '⏨'
hebrew = 'ℵℶℷℸ'
reciprocal = '⅟'
increment = '∆'
nabla = '∇'
nabla_italic = '𝛻'
nabla_bold = '𝛁'
nabla_bold_sans_serif = '𝝯'
nabla_bold_italic = '𝜵'
nabla_bold_italic_sans_serif = '𝞩'
partial = '∂'
partial_bold = '𝛛'
partial_italic = '𝜕'
partial_bold_italic = '𝝏'
partial_sans_serif_bold = '𝞉'
partial_sans_serif_bold_italic = '𝟃'
from . import operator
for_all = '∀'
complement = '∁'
exists = '∃'
exists_stroke = '∄'
proportional = '∝'
infinity = '∞'
prime = '′″‴⁗'
prime_reversed = '‵‶‷'
wreath_product = '≀'
therefore = '∴'
because = '∵'
ratio = '∶'
proportion = '∷'
angle = '∠'
plus = '+'
plus_double = '⧺'
plus_triple = '⧻'
plus_dot = '∔'
plus_underbar = '±'
plus_overbar = '∓'
plus_overbar_double = '⩱'
plus_underbar_double = '⩲'
plus_squared = '⊠'
plus_circled = '⊕'
plus_big_circled = '⨁'
bar = '−'
tilde = '~'
tilde_stroke = '≁'
tilde_reverse = '∽'
bar_bar = '='
bar_bar_doubled = '⩵'
bar_bar_tripled = '⩶'
bar_bar_stroke = '≠'
bar_tilde = '≂'
tilde_bar = '≃'
tilde_bar_stroke = '≄'
tilde_reverse_bar = '⋍'
tilde_tilde = '≈'
tilde_tilde_stroke = '≉'
bar_bar_bar = '≡'
bar_bar_bar_stroke = '≢'
bar_bar_tilde = '⩳'
tilde_bar_bar = '≅'
tilde_bar_bar_stroke = '≇≆'
tilde_reverse_bar_bar = '≌'
tilde_bar_tilde = '⩬'
tilde_tilde_bar = '≊'
tilde_tilde_tilde = '≋'
bar_bar_bar_bar = '≣'
tilde_tilde_bar_bar = '⩰'
bar_overdot = '∸'
bar_squared = '⊟'
bar_circled = '⊖'
times = '×'
times_big = '⨉'
times_squared = '⊞'
times_circled = '⊗'
times_big_circled = '⨂'
division_slash = '∕'
division_sign = '÷'
fraction = '⁄'
cross_product = '⨯'
coproduct = '⨿'
interior_product = '⨼'
interior_right = '⨽'
n_ary_product = '∏'
n_ary_coproduct = '∐'
n_ary_summation = '∑'
set_minus = '∖'
from . import wedge
from . import curve
from . import cup
solidus = '/\\'
solidus_double = '⫽'
solidus_big = '⧸⧹'
solidus_overbar = '⧶'
solidus_dash = '⧷'
solidus_circled = '⦸'
from . import in_
from . import tack
triangle = '⊲⊳'
triangle_underbar = '⊴⊵'
triangle_stroke = '⋪⋫'
triangle_stroke_underbar = '⋬⋭'
triangle_big = '⨞'
from . import box
from . import integral
from . import divides
from . import parallel
vertical_line = ''
vertical_line_white = '⫾'
vertical_line_big_white = '⫿'
vertical_line_double = '‖'
vertical_bar_circled = '⦶'
intercalate = '⊺'
perpendicular = '⟂'
empty_set = '∅'
diameter = '⌀'
numero = '№'
euler_constant = 'ℇ'
dotless_italic_i = '𝚤'
dotless_italic_j = '𝚥'
shuffle_product = '⧢'
tiny = '⧾'
miny = '⧿'
degree = '°'
not_ = '¬'
not_reversed = '⌐'
not_turned = '⌙'
from . import big_sigma
circled_division_slash = '⊘'
circled_division_sign = '⨸'
circled_equal = '⊜'
circled_parallel = '⦷'
circled_perpendicular = '⦹'
circled_less_than = None
circled_greater_than = None
circled_triangle = '⎊'
asterisk_squared = '⧆'
circle_squared = '⧇'
square_squared = '⧈'
from . import ellipsis
braille = '⠀⠁⠂⠃⠄⠅⠆⠇⠈⠉⠊⠋⠌⠍⠎⠏⠐⠑⠒⠓⠔⠕⠖⠗⠘⠙⠚⠛⠜⠝⠞⠟⠠⠡⠢⠣⠤⠥⠦⠧⠨⠩⠪⠫⠬⠭⠮⠯⠰⠱⠲⠳⠴⠵⠶⠷⠸⠹⠺⠻⠼⠽⠾⠿⡀⡁⡂⡃⡄⡅⡆⡇⡈⡉⡊⡋⡌⡍⡎⡏⡐⡑⡒⡓⡔⡕⡖⡗⡘⡙⡚⡛⡜⡝⡞⡟⡠⡡⡢⡣⡤⡥⡦⡧⡨⡩⡪⡫⡬⡭⡮⡯⡰⡱⡲⡳⡴⡵⡶⡷⡸⡹⡺⡻⡼⡽⡾⡿⢀⢁⢂⢃⢄⢅⢆⢇⢈⢉⢊⢋⢌⢍⢎⢏⢐⢑⢒⢓⢔⢕⢖⢗⢘⢙⢚⢛⢜⢝⢞⢟⢠⢡⢢⢣⢤⢥⢦⢧⢨⢩⢪⢫⢬⢭⢮⢯⢰⢱⢲⢳⢴⢵⢶⢷⢸⢹⢺⢻⢼⢽⢾⢿⣀⣁⣂⣃⣄⣅⣆⣇⣈⣉⣊⣋⣌⣍⣎⣏⣐⣑⣒⣓⣔⣕⣖⣗⣘⣙⣚⣛⣜⣝⣞⣟⣠⣡⣢⣣⣤⣥⣦⣧⣨⣩⣪⣫⣬⣭⣮⣯⣰⣱⣲⣳⣴⣵⣶⣷⣸⣹⣺⣻⣼⣽⣾⣿'
braille_alternate = '⠀⠁⠈⠉⠂⠃⠊⠋⠐⠑⠘⠙⠒⠓⠚⠛⠄⠅⠌⠍⠆⠇⠎⠏⠔⠕⠜⠝⠖⠗⠞⠟⠠⠡⠨⠩⠢⠣⠪⠫⠰⠱⠸⠹⠲⠳⠺⠻⠤⠥⠬⠭⠦⠧⠮⠯⠴⠵⠼⠽⠶⠷⠾⠿⡀⡁⡈⡉⡂⡃⡊⡋⡐⡑⡘⡙⡒⡓⡚⡛⡄⡅⡌⡍⡆⡇⡎⡏⡔⡕⡜⡝⡖⡗⡞⡟⡠⡡⡨⡩⡢⡣⡪⡫⡰⡱⡸⡹⡲⡳⡺⡻⡤⡥⡬⡭⡦⡧⡮⡯⡴⡵⡼⡽⡶⡷⡾⡿⢀⢁⢈⢉⢂⢃⢊⢋⢐⢑⢘⢙⢒⢓⢚⢛⢄⢅⢌⢍⢆⢇⢎⢏⢔⢕⢜⢝⢖⢗⢞⢟⢠⢡⢨⢩⢢⢣⢪⢫⢰⢱⢸⢹⢲⢳⢺⢻⢤⢥⢬⢭⢦⢧⢮⢯⢴⢵⢼⢽⢶⢷⢾⢿⣀⣁⣈⣉⣂⣃⣊⣋⣐⣑⣘⣙⣒⣓⣚⣛⣄⣅⣌⣍⣆⣇⣎⣏⣔⣕⣜⣝⣖⣗⣞⣟⣠⣡⣨⣩⣢⣣⣪⣫⣰⣱⣸⣹⣲⣳⣺⣻⣤⣥⣬⣭⣦⣧⣮⣯⣴⣵⣼⣽⣶⣷⣾⣿'
from . import line_extension
from . import line
third_left = '🯏🯎█'
eighth_lower = '▁▂▃▄▅▆▇█'
eighth_upper = '▔🮂🮃▀🮄🮅🮆█'
eighth_left = '▏▎▍▌▋▊▉█'
eighth_right = '▕🮇🮈▐🮉🮊🮋█'
from . import shade
one_sixteenth = '𜺐𜺑𜺒𜺓𜺔𜺕𜺖𜺗𜺘𜺙𜺚𜺛𜺜𜺝𜺞𜺟'
one_eighth_vertical = '▏🭰🭱🭲🭳🭴🭵▕'
one_eighth_horizontal = '▔🭶🭷🭸🭹🭺🭻▁'
quadrant = '▘▝▀▖▌▞▛▗▚▐▜▄▙▟█'
quadrant_separated = '𜰡𜰢𜰣𜰤𜰥𜰦𜰧𜰨𜰩𜰪𜰫𜰬𜰭𜰮𜰯'
sextant = '🬀🬁🬂🬃🬄🬅🬆🬇🬈🬉🬊🬋🬌🬍🬎🬏🬐🬑🬒🬓▌🬔🬕🬖🬗🬘🬙🬚🬛🬜🬝🬞🬟🬠🬡🬢🬣🬤🬥🬦🬧▐🬨🬩🬪🬫🬬🬭🬮🬯🬰🬱🬲🬳🬴🬵🬶🬷🬸🬹🬺🬻█'
sextant_separated = '𜹑𜹒𜹓𜹔𜹕𜹖𜹗𜹘𜹙𜹚𜹛𜹜𜹝𜹞𜹟𜹠𜹡𜹢𜹣𜹤𜹥𜹦𜹧𜹨𜹩𜹪𜹫𜹬𜹭𜹮𜹯𜹰𜹱𜹲𜹳𜹴𜹵𜹶𜹷𜹸𜹹𜹺𜹻𜹼𜹽𜹾𜹿𜺀𜺁𜺂𜺃𜺄𜺅𜺆𜺇𜺈𜺉𜺊𜺋𜺌𜺍𜺎𜺏'
octant = '𜺨𜺫🮂𜴀▘𜴁𜴂𜴃𜴄▝𜴅𜴆𜴇𜴈▀𜴉𜴊𜴋𜴌🯦𜴍𜴎𜴏𜴐𜴑𜴒𜴓𜴔𜴕𜴖𜴗𜴘𜴙𜴚𜴛𜴜𜴝𜴞𜴟🯧𜴠𜴡𜴢𜴣𜴤𜴥𜴦𜴧𜴨𜴩𜴪𜴫𜴬𜴭𜴮𜴯𜴰𜴱𜴲𜴳𜴴𜴵🮅𜺣𜴶𜴷𜴸𜴹𜴺𜴻𜴼𜴽𜴾𜴿𜵀𜵁𜵂𜵃𜵄▖𜵅𜵆𜵇𜵈▌𜵉𜵊𜵋𜵌▞𜵍𜵎𜵏𜵐▛𜵑𜵒𜵓𜵔𜵕𜵖𜵗𜵘𜵙𜵚𜵛𜵜𜵝𜵞𜵟𜵠𜵡𜵢𜵣𜵤𜵥𜵦𜵧𜵨𜵩𜵪𜵫𜵬𜵭𜵮𜵯𜵰𜺠𜵱𜵲𜵳𜵴𜵵𜵶𜵷𜵸𜵹𜵺𜵻𜵼𜵽𜵾𜵿𜶀𜶁𜶂𜶃𜶄𜶅𜶆𜶇𜶈𜶉𜶊𜶋𜶌𜶍𜶎𜶏▗𜶐𜶑𜶒𜶓▚𜶔𜶕𜶖𜶗▐𜶘𜶙𜶚𜶛▜𜶜𜶝𜶞𜶟𜶠𜶡𜶢𜶣𜶤𜶥𜶦𜶧𜶨𜶩𜶪𜶫▂𜶬𜶭𜶮𜶯𜶰𜶱𜶲𜶳𜶴𜶵𜶶𜶷𜶸𜶹𜶺𜶻𜶼𜶽𜶾𜶿𜷀𜷁𜷂𜷃𜷄𜷅𜷆𜷇𜷈𜷉𜷊𜷋𜷌𜷍𜷎𜷏𜷐𜷑𜷒𜷓𜷔𜷕𜷖𜷗𜷘𜷙𜷚▄𜷛𜷜𜷝𜷞▙𜷟𜷠𜷡𜷢▟𜷣▆𜷤𜷥█'
