from . import circle
from . import ellipse
from . import triangle
from . import pointer
from . import square
from . import rectangle
from . import parallelogram
from . import diamond
from . import lozenge
from . import cusp
from . import pentagon
from . import star
from . import hexagon
from . import octagon
