#!/bin/sh

# exit if anything goes wrong
set -e

# ------------------------------------------------------------------------------
echo step 1: copy handwritten

echo removing src/
# 🙀🙀🙀 an rm command!!!! with a -r!!!    omgomgomgomgomgomgomgomgomg
# lol ok so we have to be careful wit dis
# make sure youre IN    THE    RIGHT    DIRECTORY when youre doing this
# here, ill make sure for you
[ -d handwritten/ ] || {
	echo "you must be in same directory as generate_src to do \`rm -r src/\`"
	exit 1
}
rm -r src/

echo copying src/ to handwritten/
cp -r handwritten/ src/
# ------------------------------------------------------------------------------
echo step 2: generate code

echo mkdir src/daamath/constants/
mkdir src/daamath/constants/

echo mkdir src/daamath/unicode/
mkdir src/daamath/unicode/

echo cd to generators/
cd generators/

echo generating unicode/*.py
python 'generate unicode.py'

echo generating constants/
./generate\ constants

echo fixing implementation quirks
./quirk_fixer

echo cd back to ../
cd ../
# ------------------------------------------------------------------------------
